import type { GameEvent, Person, Task } from './types';

export const persons: Person[] = [
  {
    id: 'mario',
    name: 'Mario',
    role: 'Especialista en Datos y Reportes',
    description: 'Excelente con números y análisis profundo. Se estresa con interrupciones y clientes enojados.',
    modifiers: {
      tech: 0.5,
      analysis: 0.8,
      social: 1.8,
      emotional: 2.5,
      ambiguity: 1.5,
      urgency: 1.2,
    },
  },
  {
    id: 'maria',
    name: 'María',
    role: 'Gestora de Clientes y Equipo',
    description: 'Maneja conflictos y personas con facilidad. Se abruma si le das más de 3 tareas a la vez.',
    modifiers: {
      tech: 1.8,
      analysis: 1.5,
      social: 0.5,
      emotional: 0.8,
      ambiguity: 1.0,
      urgency: 0.8,
    },
    hard_constraints: {
      max_active_tasks: 3,
    },
  },
  {
    id: 'erika',
    name: 'Erika',
    role: 'Coordinadora de Calidad y Procesos',
    description: 'Detallista y estructurada. Sufre mucho cuando hay urgencias extremas o falta de información.',
    modifiers: {
      tech: 1.0,
      analysis: 0.5,
      social: 1.0,
      emotional: 1.0,
      ambiguity: 2.5,
      urgency: 2.0,
    },
  },
];

export const round1Tasks: Task[] = [
  {
    id: 't1',
    title: 'Preparar reporte de ventas mensual',
    description: 'Combinar datos de distintas fuentes para obtener un panorama claro. Requiere mucha concentración.',
    demand_tech: 4,
    demand_analysis: 5,
    demand_social: 0,
    demand_emotional: 0,
    ambiguity: 1,
    urgency: 3,
    duration_points: 4,
    switching_penalty: 2,
    risk_if_wrong: 4,
    stakeholder_exposure: 'medio',
  },
  {
    id: 't2',
    title: 'Atender queja de cliente VIP',
    description: 'Un cliente importante está muy molesto. Requiere tacto, paciencia y una solución rápida.',
    demand_tech: 0,
    demand_analysis: 1,
    demand_social: 5,
    demand_emotional: 5,
    ambiguity: 2,
    urgency: 5,
    duration_points: 2,
    switching_penalty: 1,
    risk_if_wrong: 5,
    stakeholder_exposure: 'alto',
  },
  {
    id: 't3',
    title: 'Organizar fiesta de fin de año',
    description: 'Coordinar múltiples detalles y opiniones encontradas para un evento de toda la empresa.',
    demand_tech: 0,
    demand_analysis: 2,
    demand_social: 4,
    demand_emotional: 1,
    ambiguity: 5,
    urgency: 2,
    duration_points: 3,
    switching_penalty: 2,
    risk_if_wrong: 2,
    stakeholder_exposure: 'medio',
  },
  {
    id: 't4',
    title: 'Revisar facturas con errores',
    description: 'Encontrar inconsistencias ocultas en un gran volumen de documentos. Un trabajo meticuloso.',
    demand_tech: 2,
    demand_analysis: 5,
    demand_social: 0,
    demand_emotional: 0,
    ambiguity: 1,
    urgency: 2,
    duration_points: 5,
    switching_penalty: 2,
    risk_if_wrong: 4,
    stakeholder_exposure: 'bajo',
  },
  {
    id: 't5',
    title: 'Idear nueva campaña de marketing',
    description: 'Generar conceptos creativos desde cero. Mucha libertad, pero ninguna dirección clara.',
    demand_tech: 1,
    demand_analysis: 2,
    demand_social: 4,
    demand_emotional: 1,
    ambiguity: 5,
    urgency: 2,
    duration_points: 4,
    switching_penalty: 2,
    risk_if_wrong: 2,
    stakeholder_exposure: 'medio',
  },
  {
    id: 't6',
    title: 'Actualizar manual de empleado',
    description: 'Traducir normativas densas a un lenguaje claro para todo el equipo.',
    demand_tech: 1,
    demand_analysis: 5,
    demand_social: 1,
    demand_emotional: 0,
    ambiguity: 2,
    urgency: 1,
    duration_points: 4,
    switching_penalty: 3,
    risk_if_wrong: 3,
    stakeholder_exposure: 'bajo',
  },
];

export const round2Tasks: Task[] = [
  {
    id: 't7',
    title: 'Negociar descuento con proveedor',
    description: 'Convencer a un socio difícil de cambiar sus condiciones. Una conversación tensa.',
    demand_tech: 0,
    demand_analysis: 2,
    demand_social: 5,
    demand_emotional: 4,
    ambiguity: 3,
    urgency: 4,
    duration_points: 3,
    switching_penalty: 2,
    risk_if_wrong: 4,
    stakeholder_exposure: 'alto',
  },
  {
    id: 't8',
    title: 'Resolver conflicto entre empleados',
    description: 'Mediar en una disputa interna que está afectando el clima laboral. Requiere mucha empatía.',
    demand_tech: 0,
    demand_analysis: 1,
    demand_social: 5,
    demand_emotional: 5,
    ambiguity: 3,
    urgency: 5,
    duration_points: 3,
    switching_penalty: 2,
    risk_if_wrong: 4,
    stakeholder_exposure: 'medio',
  },
  {
    id: 't9',
    title: 'Auditoría sorpresa de gastos',
    description: 'Rastrear discrepancias financieras bajo presión de tiempo. Cada detalle cuenta.',
    demand_tech: 3,
    demand_analysis: 5,
    demand_social: 0,
    demand_emotional: 0,
    ambiguity: 2,
    urgency: 4,
    duration_points: 5,
    switching_penalty: 1,
    risk_if_wrong: 5,
    stakeholder_exposure: 'bajo',
  },
  {
    id: 't10',
    title: 'Crear presentación para inversores',
    description: 'Sintetizar información compleja en una historia visual convincente para una audiencia crítica.',
    demand_tech: 4,
    demand_analysis: 4,
    demand_social: 1,
    demand_emotional: 2,
    ambiguity: 3,
    urgency: 5,
    duration_points: 4,
    switching_penalty: 3,
    risk_if_wrong: 5,
    stakeholder_exposure: 'alto',
  },
  {
    id: 't11',
    title: 'Responder a crisis en redes',
    description: 'Contener una situación pública que escala rápidamente. Cada palabra será analizada.',
    demand_tech: 1,
    demand_analysis: 1,
    demand_social: 5,
    demand_emotional: 5,
    ambiguity: 4,
    urgency: 5,
    duration_points: 2,
    switching_penalty: 2,
    risk_if_wrong: 5,
    stakeholder_exposure: 'alto',
  },
  {
    id: 't12',
    title: 'Planificar mudanza de oficina',
    description: 'Orquestar un cambio logístico masivo con muchas piezas móviles y poca certeza.',
    demand_tech: 1,
    demand_analysis: 4,
    demand_social: 3,
    demand_emotional: 1,
    ambiguity: 5,
    urgency: 2,
    duration_points: 4,
    switching_penalty: 2,
    risk_if_wrong: 3,
    stakeholder_exposure: 'medio',
  },
];

export const round3Tasks: Task[] = [
  {
    id: 't13',
    title: 'Cliente principal amenaza con irse',
    description: 'Salvar una relación clave que pende de un hilo. Alta presión y emociones a flor de piel.',
    demand_tech: 1,
    demand_analysis: 2,
    demand_social: 5,
    demand_emotional: 5,
    ambiguity: 4,
    urgency: 5,
    duration_points: 4,
    switching_penalty: 3,
    risk_if_wrong: 5,
    stakeholder_exposure: 'alto',
  },
  {
    id: 't14',
    title: 'Caída del sistema de ventas',
    description: 'Restaurar un servicio crítico mientras el reloj corre. Diagnóstico complejo bajo estrés extremo.',
    demand_tech: 5,
    demand_analysis: 5,
    demand_social: 1,
    demand_emotional: 3,
    ambiguity: 4,
    urgency: 5,
    duration_points: 5,
    switching_penalty: 2,
    risk_if_wrong: 5,
    stakeholder_exposure: 'alto',
  },
  {
    id: 't15',
    title: 'Redactar política de teletrabajo',
    description: 'Definir reglas justas para una situación donde todos tienen expectativas diferentes.',
    demand_tech: 0,
    demand_analysis: 5,
    demand_social: 2,
    demand_emotional: 1,
    ambiguity: 4,
    urgency: 2,
    duration_points: 4,
    switching_penalty: 2,
    risk_if_wrong: 3,
    stakeholder_exposure: 'medio',
  },
  {
    id: 't16',
    title: 'Analizar presupuesto anual',
    description: 'Navegar por un mar de números para encontrar oportunidades de ahorro. Puramente analítico.',
    demand_tech: 4,
    demand_analysis: 5,
    demand_social: 0,
    demand_emotional: 0,
    ambiguity: 2,
    urgency: 3,
    duration_points: 5,
    switching_penalty: 2,
    risk_if_wrong: 4,
    stakeholder_exposure: 'bajo',
  },
  {
    id: 't17',
    title: 'Entrevistar candidatos urgentes',
    description: 'Evaluar a múltiples personas en tiempo récord para llenar un vacío crítico en el equipo.',
    demand_tech: 0,
    demand_analysis: 2,
    demand_social: 5,
    demand_emotional: 3,
    ambiguity: 2,
    urgency: 5,
    duration_points: 4,
    switching_penalty: 1,
    risk_if_wrong: 4,
    stakeholder_exposure: 'medio',
  },
  {
    id: 't18',
    title: 'Revisar contrato legal complejo',
    description: 'Analizar un documento denso para proteger a la empresa de riesgos ocultos.',
    demand_tech: 1,
    demand_analysis: 5,
    demand_social: 0,
    demand_emotional: 0,
    ambiguity: 3,
    urgency: 2,
    duration_points: 5,
    switching_penalty: 3,
    risk_if_wrong: 5,
    stakeholder_exposure: 'bajo',
  },
];

export const events: GameEvent[] = [
  {
    id: 'e1',
    title: 'Rumor de despidos en la oficina',
    description: 'El equipo está nervioso. Todas las tareas que involucran personas ahora consumen más energía emocional.',
    round: 2,
    effect: (tasks) =>
      tasks.map((task) =>
        task.demand_social > 2 ? { ...task, demand_emotional: Math.min(5, task.demand_emotional + 2) } : task
      ),
  },
  {
    id: 'e2',
    title: 'Corte de internet general',
    description: 'Sin internet, todo es un caos. Las tareas analíticas y técnicas se vuelven más urgentes y confusas.',
    round: 3,
    effect: (tasks) =>
      tasks.map((task) =>
        task.demand_analysis > 2 || task.demand_tech > 2
          ? { ...task, ambiguity: Math.min(5, task.ambiguity + 2), urgency: Math.min(5, task.urgency + 1) }
          : task
      ),
  },
];
